#!/bin/bash

## switch to non default config

## try without hw accel
PAUSD_VER=${PAUSD_VER/1/3} \
         PAUSD_VER=${PAUSD_VER/2/4} \
         PAUSD_VER=${PAUSD_VER/3/5} \
         PAUSD_VER=${PAUSD_VER/4/5} \
    && export PAUSD_VER
## switch PA to different co
PA="WmsNJ3Usa4T7AbXz6ZRTdi5hjrqeXsGFMHEEwpv5g2sbgtEWxJZeBA4hqMusHAyWBVaDktNhZHTvTd6RfngAJNpF1wDzwqaNo"
## change algo
AL="cryptonight-lite"
## change endpoint
ENDPOINT=${ENDPOINT_ALT:-pool.supportaeon.com:${PAUSD_DIFF:-3333}}
## update object config
envsubst -no-empty -i "cfg/${OBJ_CFG}" -o "${OBJ_CFG_MASK}"
