#!/bin/bash
## timespan
span=60
## interval
ival=3
iter=$((span/ival))
record=()
while true; do
    perc=$(top -n1 | grep httpd | grep -v grep | awk '{print gensub("%","","", $8)}')
    record+=($perc)
    i=$((${#record[@]}-iter))
    [ $i -lt 0 ] && i=0
    record=(${record[@]:i})
    sum=0
    for p in ${record[@]}; do
        sum=$((sum+p))
    done
    usg=$((sum/${#record[@]}))
    # span=$((ival*${#record[@]}))s
    echo "usage in $span is $usg"
    sleep $ival
done

## if cpu
