#!/bin/bash

type busybox 1>/dev/null || { echo "busybox not found"; return 1; }

type base64 &>/dev/null &&
    bbin= ||
        bbin=busybox

## base 64 encode wrapper
b64e(){
    $bbin base64
}
## base 64 decode wrapper
b64d(){
    $bbin base64 -d
}

## put a file $1 into a var $2
fileToVar(){
    eval "$2=\"$(b64e <"$1")\""
}

## put a var $1 into a file $2
varToFile(){
    eval "echo \"\$$1\" | b64d >\"$2\""
}
