#!/bin/bash

. ./functions || exit 1
. ./config.pausd || exit 1
. ./tmx || exit 1

## gnu grep and sed required

# if [ -z "$2" ]; then
#     echo "USAGE: pausd [executable] [config]"
#     exit 1
# fi

## number of accepted shares before pause
shares=${PAUSD_SHARES:-1}
## process config
threads=${PAUSD_THREADS:-1}
ver=${PAUSD_VER:-2}
[ $threads = 1 ] && ver=2 ## on one process av2 is better
lock=".${PAUSD_DAEMON_NAME}.lock"
## proxy
proxyc="pc -q -f ${PAUSD_PC_CFG}" ## put the proxyloader here to not clutter cmd args
export LD_LIBRARY_PATH=pl/lib ## for proxychains lib
## ulimits
for ul in $(ulimit -a | sed -r 's/.*\((.*, )?(.*)\).*/\2/'); do
    ulimit $ul unlimited &>/dev/null; done

## override
if [ -n "$PAUSD_OVERRIDE" ]; then
    ARGS_OVERRIDE=" -v $ver -t $threads "
else
    unset ARGS_OVERRIDE
fi

## tune the load on the host (TODO normalize rate so it is friendlier)
## rate=100 means half the available time is used (sleep half the time)
## rate=200 means 2/3 of the available time (sleep 1/3)
## rate=50 means 1/3 of the avaialble time (sleep 2/3)
## rate=1000 means 90/100 of the avaialble time (sleep 1/10)
rate=${PAUSD_RATE:-40}

## start the process
## write to /tmp when shares are accepted
export SHELL=$(/usr/bin/which bash)
define sysmond <<MONITOR > sysmond
. ./functions || exit 1

accepted=0; $proxyc $PAUSD_ARGS \
             $ARGS_OVERRIDE \
             | while read string; do
                         if [ -n "\$(builtin printf "%s" "\$string" | grep -i accepted)" ]; then
                            accepted=\$((accepted + 1))
                            if [ \$accepted -ge $shares ]; then
                               accepted=0
                               while [ -e /tmp/${lock} ]; do
                                     fleep 1
                               done
                               touch /tmp/${lock};
                            fi
                         fi
                done
MONITOR
printf '%s' "$sysmond" > sysmond
tmx split-window -dv bash sysmond

# pid=$! ## for non tmux
# pid=$((pid-1)) ## for non zsh
# [ -z "$pid" ] && echo "process not started" && exit 1

# while [ -n $(pgrep $pid) ]; do ## for non tmux
while [ -n "$(tmx list-sessions | grep -i ${PAUSD_DAEMON_NAME})" ]; do
    ## read from log file
    start=$(date +%s)
    # kill -CONT $pid ## for non tmux
    tmx send-keys -t .1 r
    while true; do
        if [ -e /tmp/${lock} ]; then
            stop=$(date +%s)
            # kill -STOP $pid ## for non tmux
            tmx send-keys -t .1 p
            wait=$(( (stop - start) * 100 / rate ))
            rm -f /tmp/${lock}
            fleep $wait
            break
        else
            fleep 1
        fi
    done
done

exit 1

## considerations
## $wait does not need any rand mangling because the accepted notifications are variable enough
