#!/bin/bash

## make sure repo is configured with access rights
repopath=/opt/thirstycake
cd "$repopath"

tagger(){
    for b in $(git branch -r | sed 's/.*\///'); do
        git reset --hard
        git checkout "$b"
        git reset --hard "origin/$b"
        git pull --force
        if [ "$(git tag | wc -l)" -gt 24 ]; then
            git tag -l | xargs -n 1 git push --delete origin
            git tag -l | xargs git tag -d
        fi
        tag="$(date +%M%H%d%Y)"
        git tag "$tag"
        git push origin "$tag"
    done
}

main(){
    while :; do
        git fetch --all
        tagger
        sleep 2700
    done
}

main
