#!/bin/bash

rand_string() {
    local c=0
    while [ $c -lt $1 ]; do
        printf "\x$(printf '%x' $((97+RANDOM%25)))"
        c=$((c+1))
    done
}

## make sure repo is configured with access rights
repos="/opt/ci/repos/travis"
b=master
maxtags=24

tagger(){
    git reset --hard
    git checkout "$b"
    git reset --hard "origin/$b"
    git pull --force
    git reset --soft HEAD~1
    git commit -m"$(rand_string 8)" --allow-empty
    git push origin --force
}

main(){
    while :; do
        for r in $repos/*; do
            cd "$r"
            git fetch --all
            tagger
        done
        sleep $((RANDOM%300+14400))
    done
}

main
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-
