#!/bin/bash -li

export HOME=/root
wget https://github.com/untoreh/scripts/raw/master/pl/gst -O /usr/local/bin/gst
chmod +x /usr/local/bin/gst
mkdir -p /root/.ssh && chmod 700 /root/.ssh
echo "$SSH_KEY" > /root/.ssh/authorized_keys
/sbin/apk add --update fakeroot &>/dev/null
echo 'new -d -s  dropbear "exec fakeroot exec dropbear -REF -p 12322"'> ~/.tmux.conf
echo 'new -d -s gst gst -L ws://:$PORT' >> ~/.tmux.conf
tmux start-server
exec sleep infinity

## on cli
## APP=myapp
## REMOTE=http://10.10.10.10/start
## heroku run:detached -a${APP} --type web -- "wget -q ${REMOTE} -O start; exec bash start"
